### ISSUE TITLE
安装不清楚一些配置字段需要填什么

### ISSUE THREAD

**Issue by lmm2022** [darknightlab/wechat-bot#2]
![image](https://user-images.githubusercontent.com/44827236/215630573-abe42f0d-d95b-407f-bcce-9ff828ddd9ce.png)
你好 ，请问下z这些字段需要填什么呢  以往的一些项目只需要APIkeys 作者大大的项目多了这些不清楚怎么填 麻烦告知下 谢谢啦

**Comment by lmm2022** [comment]
@canoziia

**Comment by canoziia** [comment]
其实是我太久没更新了，现在更新了，只需要openai apiKey

**Comment by lmm2022** [comment]
好的 谢谢啦

**Comment by lmm2022** [comment]
![image](https://user-images.githubusercontent.com/44827236/217186628-d07290d9-27b8-4278-92e3-5340a7575e46.png)
作者大大 启动报错 安装依赖是都ok的
